### ISSUE TITLE
Can't use `constructor` key in the object

### ISSUE THREAD

**Issue by Rigidoont** [mesqueeb/flatten-anything#15]
Presence of the `constructor`  key in the object seems to break flattening. No errors are produced, the object simply does not get flattened.

**Comment by mesqueeb** [comment]
@Gidoont it might be a reserved keyword for JS to know how an object was made, as a plain object or as a class instance.

I'd advice you to not use the key called `constructor` but if you must then..... I'm not sure how to fix it yet :P PRs welcome though!

**Comment by Rigidoont** [comment]
Unfortunately, it's not up to me whether to use such key or not. I'm receiving a JSON and have to do some work on it.

**Comment by Rigidoont** [comment]
@mesqueeb I think here's the issue - https://github.com/mesqueeb/is-what/blob/production/src/index.ts#L46

`isPlainObject` method is used in https://github.com/mesqueeb/flatten-anything/blob/production/src/index.ts#L11

It does not recognize the object as a plain one if the `constructor` property is overridden.

**Comment by Rigidoont** [comment]
PR - https://github.com/mesqueeb/is-what/pull/24

**Comment by mesqueeb** [comment]
@Gidoont thank you very much! it's released in latest version v3.0.3
